version: '3.9'

services:
  db:
    image: mysql:latest
    container_name: DB-host
    build:
      context: .
      dockerfile: docker/mySQL/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: contact_practice
      MYSQL_USER: user
      MYSQL_PASSWORD: user-pass
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./db/data:/var/lib/mysql
    - ./db/sql:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306
